services:
  web:
    build: .
    image: fileuploadportal
    container_name: fileuploadportal
    ports:
      - "5000:80"
    volumes:
      # Mount uploads directory for persistent storage
      - ./uploads:/app/uploads
    environment:
      # Admin password - change this or use environment variable
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    restart: unless-stopped
    networks:
      - fileuploadportal-network

networks:
  fileuploadportal-network:
    name: fileuploadportal-network
    driver: bridge

